### ISSUE TITLE
Problem with format cell: Date

### ISSUE THREAD

**Issue by thearabbit** [andy51002000/excel-to-json#2]
- Excel
![image](https://user-images.githubusercontent.com/4495160/44389194-67ac9680-a554-11e8-9f5a-706c7caafe39.png)

- Out

![image](https://user-images.githubusercontent.com/4495160/44389209-72672b80-a554-11e8-9e64-727cd84e6ee4.png)

Problem with `data, time` column???

**Comment by andy51002000** [comment]
@thearabbit 

By default, Excel stores datetime as floating point number. It needs to convert the value to a proper datetime format. I am going to add this in the next version. Currently, you could convert it by youself.

function getJsDateFromExcel(excelDate) { return new Date(Math.round((excelDate - (25567 + 2))*86400)*1000); }

**Comment by thearabbit** [comment]
very thanks 👍
